import { CATEGORIES } from "./schema";
import { getChangedEntries } from "./state";

export function generateConfig(): string {
  const changed = new Map(getChangedEntries());

  if (changed.size === 0) {
    return "# All settings at defaults.\n# Change some settings to generate config\n";
  }

  const lines: string[] = ["# kitty.conf", "# Generated by kitty-conf", ""];

  for (const category of CATEGORIES) {
    const categoryLines: string[] = [];
    for (const setting of category.settings) {
      if (changed.has(setting.key)) {
        categoryLines.push(`${setting.key} ${changed.get(setting.key)}`);
      }
    }
    if (categoryLines.length > 0) {
      lines.push(`# ${category.title}`);
      lines.push(...categoryLines);
      lines.push("");
    }
  }

  return lines.join("\n");
}
