import { CATEGORIES } from "./schema";
import { getChangedEntries, getFileName, getMappings } from "./state";

export function generateConfig(): string {
  const changed = new Map(getChangedEntries());
  const validMappings = getMappings().filter((m) => m.keys && m.action);

  if (changed.size === 0 && validMappings.length === 0) {
    return "# All settings at defaults.\n# Change some settings to generate config\n";
  }

  const lines: string[] = ["# Generated by kitty-conf (https://kitty-conf.balintb.com/)", ""];

  for (const category of CATEGORIES) {
    const categoryLines: string[] = [];
    for (const setting of category.settings) {
      if (changed.has(setting.key)) {
        let value = changed.get(setting.key)!;
        if (setting.type === "file" && value.startsWith("data:")) {
          value = getFileName(setting.key) || "image.png";
          categoryLines.push(`# Use the full path to your image file`);
        }
        categoryLines.push(`${setting.key} ${value}`);
      }
    }
    if (categoryLines.length > 0) {
      lines.push(`# ${category.title}`);
      lines.push(...categoryLines);
      lines.push("");
    }
  }

  if (validMappings.length > 0) {
    lines.push("# Key Mappings");
    for (const m of validMappings) {
      const parts = ["map", m.keys, m.action];
      if (m.args) parts.push(m.args);
      lines.push(parts.join(" "));
    }
    lines.push("");
  }

  return lines.join("\n");
}
