import { CATEGORIES } from "./schema";
import { getChangedEntries, getFileName } from "./state";

export function generateConfig(): string {
  const changed = new Map(getChangedEntries());

  if (changed.size === 0) {
    return "# All settings at defaults.\n# Change some settings to generate config\n";
  }

  const lines: string[] = ["# kitty.conf", "# Generated by kitty-conf (https://kitty-conf.balintb.com/)", ""];

  for (const category of CATEGORIES) {
    const categoryLines: string[] = [];
    for (const setting of category.settings) {
      if (changed.has(setting.key)) {
        let value = changed.get(setting.key)!;
        if (setting.type === "file" && value.startsWith("data:")) {
          value = getFileName(setting.key) || "image.png";
          categoryLines.push(`# Use the full path to your image file`);
        }
        categoryLines.push(`${setting.key} ${value}`);
      }
    }
    if (categoryLines.length > 0) {
      lines.push(`# ${category.title}`);
      lines.push(...categoryLines);
      lines.push("");
    }
  }

  return lines.join("\n");
}
